using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text.Json;
using Xunit;

namespace Jellyfin.Plugin.WatchSync.Tests;

/// <summary>
/// Holds the restore to the graph this repository committed.
///
/// Without a lock file, two restores of one commit resolve whatever the feed holds on the day
/// they run, so the assembly an operator installs is decided by the feed rather than by
/// anything here, and a dependency review that passed on one run says nothing about the next.
/// The lock file fixes the graph and locked mode is what refuses to move off it.
///
/// NuGet already refuses a lock file that disagrees with the project files: it is NU1004, it
/// names the mismatch and it stops the restore. What it does not refuse is the lock file being
/// gone. A locked-mode restore with no lock file present writes a fresh one and succeeds, so
/// deleting the file removes the whole control and reddens nothing anywhere in the toolchain.
/// That is the hole these two tests close, and neither of them repeats what NU1004 already
/// says.
/// </summary>
public class LockFileTests
{
    private const string LockFileName = "packages.lock.json";

    /// <summary>
    /// The lock files are regenerated by a restore run with this command. It is named here
    /// rather than in the build properties because an XML comment may not carry two dashes in
    /// a row, and a contributor meeting NU1004 needs to be told what to run.
    /// </summary>
    private const string RegenerateCommand = "dotnet restore Jellyfin.Plugin.WatchSync.sln --force-evaluate";

    /// <summary>
    /// Every project the repository tracks carries a lock file beside it, and git tracks that
    /// too.
    ///
    /// Both halves matter and for different reasons. A lock file that is absent is regenerated
    /// by the next restore without complaint, which is measured rather than supposed. A lock
    /// file that exists on one machine and is not in the commit is the same as no lock file
    /// for everybody who clones the repository, and it is the likelier of the two mistakes
    /// because the file is written by a tool rather than typed.
    /// </summary>
    [Fact]
    public void EveryTrackedProjectHasATrackedLockFile()
    {
        var root = HeadlessGuardTests.HeadlessGuard.RepositoryRoot();
        var projects = TrackedProjects(root);
        var tracked = new HashSet<string>(TrackedPaths(root, "*" + LockFileName), StringComparer.Ordinal);

        Assert.NotEmpty(projects);

        Assert.Empty(projects
            .Select(project => project[..(project.LastIndexOf('/') + 1)] + LockFileName)
            .Where(expected => !tracked.Contains(expected))
            .Select(expected => $"{expected} is not tracked, so nothing holds the restore to a graph. Run: {RegenerateCommand}"));
    }

    /// <summary>
    /// The two properties read off the evaluated project rather than off the file that happens
    /// to set them today. Where they are declared is a detail; that every project restores in
    /// locked mode and writes a lock file is the rule, and a project overriding either of them
    /// is exactly the case a read of the shared properties file would miss.
    ///
    /// Dropping either property is a change that leaves every test green and every build
    /// working, and the first sign of it is two installs of one version behaving differently.
    /// </summary>
    [Fact]
    public void EveryTrackedProjectRestoresInLockedModeAndWritesALockFile()
    {
        var root = HeadlessGuardTests.HeadlessGuard.RepositoryRoot();

        var wrong = new List<string>();

        foreach (var project in TrackedProjects(root))
        {
            var evaluated = Properties(root, project, "RestoreLockedMode", "RestorePackagesWithLockFile");

            wrong.AddRange(evaluated
                .Where(property => !string.Equals(property.Value, "true", StringComparison.OrdinalIgnoreCase))
                .Select(property => $"{project} evaluates {property.Key} to '{property.Value}' rather than true, so its restore may resolve off the lock file."));
        }

        Assert.Empty(wrong);
    }

    /// <summary>
    /// Asks git for the tracked project files, so a project added tomorrow is covered without
    /// anybody remembering to name it here.
    /// </summary>
    /// <param name="root">The repository root.</param>
    /// <returns>The repository-relative path of each tracked project.</returns>
    internal static IReadOnlyList<string> TrackedProjects(string root) => TrackedPaths(root, "*.csproj");

    private static IReadOnlyList<string> TrackedPaths(string root, string pattern) =>
        Run(root, "git", "ls-files -- " + pattern)
            .Split('\n')
            .Select(line => line.Trim())
            .Where(line => line.Length > 0)
            .ToList();

    /// <summary>
    /// Evaluates named properties of a project through the build itself. Reading a property
    /// out of a file would prove what that file says rather than what the project resolves to.
    ///
    /// One name and several names are two output shapes rather than one. Asked for several,
    /// msbuild answers with a document under a Properties member; asked for one, it answers
    /// with the bare value and nothing around it, so a document read would fail on the value
    /// rather than on the property being unset. Both are handled here because the caller
    /// asking for one property is the likelier one and its failure would read as a broken
    /// project rather than as a helper that never met that case.
    /// </summary>
    /// <param name="root">The repository root.</param>
    /// <param name="project">The repository-relative project path.</param>
    /// <param name="names">The properties to read.</param>
    /// <returns>Each name with the value the project evaluates it to, empty where it is unset.</returns>
    internal static IReadOnlyDictionary<string, string> Properties(string root, string project, params string[] names)
    {
        var arguments = "msbuild " + project + string.Concat(names.Select(name => " -getProperty:" + name));
        var output = Run(root, "dotnet", arguments);

        if (names.Length == 1)
        {
            return new Dictionary<string, string>(StringComparer.Ordinal) { [names[0]] = output.Trim() };
        }

        using var document = JsonDocument.Parse(output);
        var properties = document.RootElement.GetProperty("Properties");

        return names.ToDictionary(
            name => name,
            name => properties.TryGetProperty(name, out var value) ? value.GetString() ?? string.Empty : string.Empty,
            StringComparer.Ordinal);
    }

    private static string Run(string root, string file, string arguments)
    {
        var start = new ProcessStartInfo(file, arguments)
        {
            WorkingDirectory = root,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true,
        };

        using var process = Process.Start(start);
        Assert.NotNull(process);

        var output = process!.StandardOutput.ReadToEnd();
        var error = process.StandardError.ReadToEnd();
        process.WaitForExit();

        Assert.True(process.ExitCode == 0, $"{file} {arguments} exited {process.ExitCode}: {error}{output}");

        return output;
    }
}
