using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Xunit;

namespace Jellyfin.Plugin.WatchSync.Tests;

/// <summary>
/// Holds the route that produces the manifest every install and every update reads.
///
/// The manifest is an index of the versions an operator may install, and it is the artefact
/// most likely to be assembled by hand at three in the morning after an address has gone.
/// #119's first condition is that the release run generates it and that nobody edits one, and
/// its fourth is that regenerating it from the release history reproduces it exactly, which is
/// what makes a repair comparable to what is being served rather than a rewrite nobody can
/// check.
///
/// The verdict is made by `.github/generate-manifest.py`, which runs on a runner and never
/// here: a fact that shelled out to it would make this suite need Python on every machine it
/// runs on, which is the headless rule's own subject and is written in
/// `Jellyfin.Plugin.WatchSync.Tests/headless-rule.md`. So what is held here is the route - that
/// the release run generates both channels, that it proves the generator bites before trusting
/// it, that it regenerates and compares the bytes, and that no manifest is committed for
/// somebody to edit. Each of those is one deletion away from a release that publishes an index
/// nobody generated, in silence.
/// </summary>
public class ManifestGeneratorTests
{
    /// <summary>
    /// Both channels are generated by the release run. A route generating one of them leaves
    /// the other address serving whatever was last put there by hand, which is the state this
    /// generator exists to end, and the missing channel is the pre-release one that fewer
    /// people would notice.
    /// </summary>
    /// <param name="channel">A channel the run has to generate.</param>
    [Theory]
    [InlineData("stable")]
    [InlineData("prerelease")]
    public void TheReleaseRunGeneratesTheManifestForEachChannel(string channel)
    {
        var publish = ManifestRoute.Publish();

        Assert.Contains(ManifestRoute.Generator, publish, StringComparison.Ordinal);
        Assert.Contains("for channel in stable prerelease", publish, StringComparison.Ordinal);
        Assert.Contains($"manifest-{channel}.json", publish, StringComparison.Ordinal);
    }

    /// <summary>
    /// The manifest is generated after the release exists rather than beside it. A manifest
    /// built before the release is created describes a history that does not yet hold the
    /// version being published, so the run would publish a release and an index that omits it,
    /// and both would look successful.
    /// </summary>
    [Fact]
    public void TheManifestIsGeneratedAfterTheReleaseExists()
    {
        var publish = ManifestRoute.Publish();

        Assert.Contains("  manifest:", publish, StringComparison.Ordinal);
        Assert.Contains("needs: release", publish, StringComparison.Ordinal);
    }

    /// <summary>
    /// The whole history is read rather than this release alone. An index generated from the
    /// newest release offers that version and hides every earlier one, and a server already on
    /// a later version is offered a downgrade by a catalog that looks complete.
    /// </summary>
    [Fact]
    public void TheRunReadsTheWholeReleaseHistory()
    {
        var publish = ManifestRoute.Publish();

        Assert.Contains("gh api --paginate", publish, StringComparison.Ordinal);
        Assert.Contains("/releases\"", publish, StringComparison.Ordinal);
    }

    /// <summary>
    /// The generator is proven on every release run. It is green on every history that has
    /// never carried one of the states it refuses, which is every history this repository has
    /// had, so a version of it gutted into a pass would look exactly like the one that works
    /// until the day it was needed.
    ///
    /// Each fixture is named rather than the step being asserted to exist, because a step still
    /// running one of them proves nothing about the arms the others are for.
    /// </summary>
    /// <param name="fixture">A path the proof step has to name.</param>
    [Theory]
    [InlineData(".github/manifest-fixtures/no-release-at-all.json")]
    [InlineData(".github/manifest-fixtures/a-tag-with-no-channel.json")]
    [InlineData(".github/manifest-fixtures/the-flag-disagrees-with-the-tag.json")]
    [InlineData(".github/manifest-fixtures/two-archives-in-one-release.json")]
    [InlineData(".github/manifest-fixtures/one-version-claimed-twice.json")]
    [InlineData(".github/manifest-fixtures/a-single-release.json")]
    [InlineData(".github/manifest-fixtures/two-channels.json")]
    [InlineData(".github/manifest-fixtures/one-channel-only.json")]
    public void TheGeneratorIsProvenOnEveryReleaseRun(string fixture)
    {
        var publish = ManifestRoute.Publish();

        Assert.Contains(ManifestRoute.Generator, publish, StringComparison.Ordinal);
        Assert.Contains(Path.GetFileName(fixture), publish, StringComparison.Ordinal);
        Assert.True(
            File.Exists(ManifestRoute.Absolute(fixture)),
            $"{fixture} is named by the proof step and is not in the tree, so that step fails on the runner rather than proving anything.");
    }

    /// <summary>
    /// The asset trees the arms are refused against are in the tree too. A history fixture
    /// alone refuses nothing about a checksum: the two arms that catch a sidecar belonging to
    /// another file, and one that is not a digest at all, are differences in the files beside
    /// the archive rather than in the release list.
    /// </summary>
    /// <param name="tree">An asset tree the proof step has to name.</param>
    [Theory]
    [InlineData(".github/manifest-fixtures/assets")]
    [InlineData(".github/manifest-fixtures/assets-checksum-of-another-file")]
    [InlineData(".github/manifest-fixtures/assets-the-checksum-is-not-a-digest")]
    [InlineData(".github/manifest-fixtures/assets-one-version-twice")]
    public void EveryAssetTreeTheProofNamesIsInTheTree(string tree)
    {
        var publish = ManifestRoute.Publish();

        Assert.Contains(Path.GetFileName(tree), publish, StringComparison.Ordinal);
        Assert.True(
            Directory.Exists(ManifestRoute.Absolute(tree)),
            $"{tree} is named by the proof step and is not in the tree, so that step fails on the runner rather than proving anything.");
    }

    /// <summary>
    /// Every fixture in the directory is named by the proof. This is the direction the two
    /// rules above cannot see: a fixture written for an arm and never run is a case somebody
    /// believes is covered, and it costs nothing to add and nothing to notice.
    /// </summary>
    [Fact]
    public void NoFixtureSitsInTheDirectoryUnrun()
    {
        var publish = ManifestRoute.Publish();
        var directory = ManifestRoute.Absolute(".github/manifest-fixtures");

        var unrun = Directory
            .EnumerateFileSystemEntries(directory)
            .Select(Path.GetFileName)
            .Where(name => name is not null)
            .Where(name => !publish.Contains(name!, StringComparison.Ordinal))
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToList();

        Assert.Empty(unrun.Select(name => $".github/manifest-fixtures/{name} is in the tree and the proof step names it nowhere, so it proves nothing about the generator."));
    }

    /// <summary>
    /// The proof runs each arm and each repair. A step that only ran the refusing fixtures
    /// would pass while the generator refused every history, including a real one, and a step
    /// that only ran the passing ones is the state this whole class exists against.
    /// </summary>
    [Fact]
    public void TheProofRunsBothDirections()
    {
        var publish = ManifestRoute.Publish();

        Assert.Contains("refuses stable \"${fixtures}/assets\" \"${fixtures}/no-release-at-all.json\"", publish, StringComparison.Ordinal);
        Assert.Contains("refuses stable \"${fixtures}/assets-checksum-of-another-file\" \"${fixtures}/a-single-release.json\"", publish, StringComparison.Ordinal);
        Assert.Contains("passes stable \"${fixtures}/assets\" \"${fixtures}/two-channels.json\"", publish, StringComparison.Ordinal);
        Assert.Contains("passes prerelease \"${fixtures}/assets\" \"${fixtures}/one-channel-only.json\"", publish, StringComparison.Ordinal);
    }

    /// <summary>
    /// The run regenerates each manifest from the same history and refuses a difference. This
    /// is #119's fourth condition asked of the real history rather than of a fixture, and the
    /// shapes that break it - a member order that follows a dictionary, a timestamp taken from
    /// the clock, an ordering that follows the order the API answered in - all produce a first
    /// run that looks perfectly correct.
    /// </summary>
    [Fact]
    public void TheRunRegeneratesEachManifestAndRefusesADifference()
    {
        var publish = ManifestRoute.Publish();

        Assert.Contains("regenerated-${channel}.json", publish, StringComparison.Ordinal);
        Assert.Contains("cmp -s \"manifest-${channel}.json\" \"regenerated-${channel}.json\"", publish, StringComparison.Ordinal);
    }

    /// <summary>
    /// No manifest is committed. The first condition of #119 is that the release run generates
    /// it and that it is never edited by hand, and a file in the tree is the invitation: it is
    /// what somebody opens when an address has gone, and an edit to it is invisible against a
    /// generated one until a server reads the two and disagrees.
    /// </summary>
    [Fact]
    public void NoManifestIsCommittedForSomebodyToEdit()
    {
        var root = HeadlessGuardTests.HeadlessGuard.RepositoryRoot();

        var committed = new[] { "manifest.json", "manifest-stable.json", "manifest-prerelease.json" }
            .Where(name => File.Exists(Path.Combine(root, name)))
            .ToList();

        Assert.Empty(committed.Select(name => $"{name} is in the repository. The manifest is generated by the release run out of the release history, so a copy in the tree is one somebody will edit."));
    }

    /// <summary>
    /// Where the two files the release run produces are read from, so a rule here judges the
    /// route this repository ships rather than a copy of it.
    /// </summary>
    internal static class ManifestRoute
    {
        /// <summary>
        /// The generator, named the way the workflow names it.
        /// </summary>
        internal const string Generator = ".github/generate-manifest.py";

        private const string Workflow = ".github/workflows/publish.yaml";

        /// <summary>
        /// The publish route this repository ships.
        /// </summary>
        /// <returns>The text of the workflow.</returns>
        internal static string Publish() => File.ReadAllText(Absolute(Workflow));

        /// <summary>
        /// A repository-relative path, resolved against the root of this checkout.
        /// </summary>
        /// <param name="relative">The path, with forward slashes.</param>
        /// <returns>The absolute path.</returns>
        internal static string Absolute(string relative)
        {
            ArgumentNullException.ThrowIfNull(relative);

            return Path.Combine(
                HeadlessGuardTests.HeadlessGuard.RepositoryRoot(),
                relative.Replace('/', Path.DirectorySeparatorChar));
        }
    }
}
